name: Build STC_editor for Windows

on:
  push:
    branches:
      - master
  release:
    types: [created]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: 6.7.3
          target: desktop
          arch: win64_msvc2019_64
          modules: qtwebengine qtpositioning qtwebchannel

      - name: Configure MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure and build (CMake + MSVC)
        run: |
          mkdir build
          cd build
          cmake .. -G "NMake Makefiles" -DCMAKE_PREFIX_PATH=%Qt6_DIR%
          nmake

      - name: Deploy Qt dependencies using windeployqt
        run: |
          windeployqt.exe build\STC_editor.exe --qmldir=. --no-compiler-runtime --verbose=2

      - name: Package zip
        run: |
          mkdir zipdir
          copy build\STC_editor.exe zipdir\
          copy build\*.dll zipdir\
          copy build\*.pak zipdir\
          if (Test-Path build\QtWebEngineProcess.exe) { copy build\QtWebEngineProcess.exe zipdir\ }
          if (Test-Path build\icudtl.dat) { copy build\icudtl.dat zipdir\ }
          if (Test-Path build\resources\*) { Copy-Item build\resources\* zipdir\ }
          if (Test-Path build\translations\*) { Copy-Item build\translations\* zipdir\ }
          7z a STC_editor-win64.zip .\zipdir\*

      - name: Upload zip as build artifact
        uses: actions/upload-artifact@v4
        with:
          name: STC_editor-win64
          path: STC_editor-win64.zip

      - name: Upload ZIP to GitHub Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: STC_editor-win64.zip
