name: Build STC_editor AppImage fo Linux (on push to master)

on:
  push:
    branches:
      - master
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies (Qt6 + build tools)
        run: |
          sudo apt update
          sudo apt install -y \
            qt6-base-dev \
            qt6-tools-dev \
            qt6-tools-dev-tools \
            qt6-webengine-dev \
            qt6-webengine-dev-tools \
            libqt6webenginecore6-bin \
            libgl-dev \
            libglu1-mesa-dev \
            libxkbcommon-dev \
            mesa-common-dev \
            build-essential \
            cmake \
            qt6-base-dev-tools \
            libuchardet-dev \
            libgtest-dev \
            libfuse2 \
            nsight-compute \
            libgconf-2-4 \
            wget

      - name: Install GCC 13 required for <format> library
        run: |
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt update
          sudo apt install -y gcc-13 g++-13
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 100 \
                                   --slave /usr/bin/g++ g++ /usr/bin/g++-13

      - name: Prepare icon
        run: |
          mkdir -p resources/icons
          cp resources/icon.png resources/icons/stc_editor.png

      - name: Create .desktop file
        run: |
          echo "[Desktop Entry]
          Name=STC Editor
          Exec=STC_editor
          Icon=stc_editor
          Type=Application
          Categories=Utility;TextEditor;" > STC_editor.desktop

      - name: Build application (CMake + Qt6)
        run: |
          mkdir -p build
          cd build
          cmake -DCMAKE_PREFIX_PATH=/usr/lib/qt6 ..
          cmake --build . --parallel

      - name: Manually copy QtWebEngineProcess and resources
        run: |
          mkdir -p build/libexec
          mkdir -p build/resources
          mkdir -p build/translations

          cp qt-runtime/resources/* build/resources/
          cp -r qt-runtime/translations build/

          echo "Searching for QtWebEngineProcess..."
          QTWEBENGINE_BIN=$(dpkg -L libqt6webenginecore6-bin | grep QtWebEngineProcess | head -n 1 || true)

          if [ -z "$QTWEBENGINE_BIN" ]; then
            echo "ERROR: QtWebEngineProcess not found via dpkg -L"
            exit 1
          fi

          echo "Found QtWebEngineProcess at: $QTWEBENGINE_BIN"
          cp "$QTWEBENGINE_BIN" build/libexec/

      - name: Move desktop and icon into build dir
        run: |
          cp STC_editor.desktop build/
          cp resources/icons/stc_editor.png build/

      - name: Download linuxdeployqt
        run: |
          wget https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
          chmod +x linuxdeployqt-continuous-x86_64.AppImage

      - name: Run linuxdeployqt
        run: |
          export PATH=/usr/lib/qt6/bin:$PATH
          ./linuxdeployqt-continuous-x86_64.AppImage build/STC_editor.desktop -appimage

      - name: Rename AppImage
        run: |
          APPIMAGE=$(ls *.AppImage | head -n 1)
          mv "$APPIMAGE" STC_editor-x86_64.AppImage

      - name: Upload AppImage artifact
        uses: actions/upload-artifact@v4
        with:
          name: STC_editor-AppImage
          path: STC_editor-x86_64.AppImage

      - name: Upload AppImage to GitHub Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: STC_editor-x86_64.AppImage

# TODO: Add running tests
# TODO: Add building for windows
# TODO: Add generating deb
