name: Test STC_editor on Linux

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies (Qt6, GTest, build tools)
        run: |
          sudo apt update
          sudo apt install -y \
            qt6-base-dev \
            qt6-tools-dev \
            qt6-tools-dev-tools \
            qt6-webengine-dev \
            qt6-webengine-dev-tools \
            libqt6webenginecore6-bin \
            libgl-dev \
            libglu1-mesa-dev \
            libxkbcommon-dev \
            mesa-common-dev \
            build-essential \
            cmake \
            qt6-base-dev-tools \
            libuchardet-dev \
            libgtest-dev \
            wget

      - name: Build tests (CMake + Qt6)
        run: |
          mkdir -p build
          cd build
          cmake -DCMAKE_PREFIX_PATH=/usr/lib/qt6 ..
          cmake --build . --parallel

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure

      - name: List CTest tests
        run: |
          cd build
          ctest -N
